# Generated by Django 3.0.6 on 2020-08-27 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forms',
            name='age',
        ),
        migrations.AddField(
            model_name='forms',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='forms',
            name='password1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='forms',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
